name: Build & Release Game

on:
  push:
    tags:
      - 'v*'  # Runs when you push a tag like v1.0.0
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build executable (Windows)
        if: runner.os == 'Windows'
        run: pyinstaller --onedir --clean --windowed --add-data "assets;assets" main.py -n asteroid

      - name: Build executable (macOS/Linux)
        if: runner.os != 'Windows'
        run: pyinstaller --onedir --clean --windowed --add-data "assets:assets" main.py -n asteroid

      - name: Package build
        run: |
          cd dist
          zip -r asteroid-${{ matrix.os }}.zip asteroid

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: asteroid-${{ matrix.os }}
          path: dist/asteroid-${{ matrix.os }}.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
